name: 🏗 Build application

on:
  push:
    branches:
      - develop
      - feature/**

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Setup node 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies 📦
        run: npm install

      - name: Build app for web 🏗
        run: npm run build

  tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Setup node 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust stable 🦀
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only) 🐧
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies 📦
        run: npm install

      - name: Build app for ${{ matrix.platform }} 🏗
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
