name: 🧪 Running e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Setup node 🔧
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies 📦
        run: npm install

      - name: Cypress run on chrome 🧪
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run start
          wait-on: 'http://localhost:4201'
          record: true
        env:
          CYPRESS_RECORD_KEY: '01dbe592-356f-404b-996c-7a3eb9ffcb81'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies 📦
        run: npm install

      - name: Cypress run on firefox 🦊
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          start: npm run start
          wait-on: 'http://localhost:4201'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
