name: 🧪 Running e2e tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1, 2 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Cypress run on chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run start
          wait-on: 'http://localhost:4201'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: '01dbe592-356f-404b-996c-7a3eb9ffcb81'

      - name: Cypress run on firefox
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
          start: npm run start
          wait-on: 'http://localhost:4201'
