name: 👕 Lint source files

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install dependencies 📦
        run: npm ci

      - name: Lint source files 👕
        run: npm run lint
